language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: m5g28nPF2mTOjyWcMSo+u3ZHYlBhxiDYJNIAZgmoQC8q0AVYiQxRqXvlCAIwe/tUlT+ad4wNb+ynhwSayfMdp5Pox1nLSuJ/kWGagHMs8cS+7WW2D3QKYrk3dDkZrPJOzwT1Ty4Bo05duMoIExxLkSPx1MbiP3MM/1riS5Y2Ef59laCZwQ4JEGKvMnKPVeESTHvV+K3T41MIMdgeGuGJbVUd54UTF0upZHeT2sqISUT3xKBOwYOmWHvX3RtRDuTengZFXR9HKtWVX6f7q/ZK6YZT5v81CVk7771+F5r9usuZZDh99LBZzTAogatRlMZQNvXiXX+2ILanXVp4WiErDJqdL+94T1Y+xhQWyUNydoPWI6nHS0onCTaP5sfpMxYZHTq8kFOvq2k9+NrhZ09KsfNXnM4UanVNx6LKhERxCO45Roo0fs6eQ/NBJGe+qdJ1iMZIdOVkL/JOwAP0Lb30ki8uKZDZ4Lz50YrHH9MLMO3XuEYcCVSYRWW4Kgq3P/jX7z5Z+9ueVDcClnpbgJDoO3IOYLiWDkRsOestFAqK6R1UGbuWKMVjzxxitdVnNIgezzXNSKPzIzdyPRT3AZj5fu6hP8P1VnJkG+UNCl2wGtiOutc7CCkHv4GKbn9NXBDtnq/Vp/3dYr5WBlnBkcTwrtCuKAnlOGHhKBBDQ4xpWts=
  app: blooming-badlands-99255
  run: rails db:migrate
